name: bundle CI
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches-ignore:
  #     - "gh-pages"

defaults:
  run:
    working-directory: ./bundle

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run unit tests
        run: "yarn test --ci"

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint files
        run: yarn lint

      - name: Check formatting
        run: yarn prettier:check
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: yarn tsc
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: guardian/actions-setup-node@main
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build package
        run: yarn build

      # - name: Save build
      #   if: github.ref == 'refs/heads/main'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: core
      #     path: core/dist
  # release:
  #   name: Release
  #   needs: [build, test, lint, types]
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false

  #     - name: Setup node
  #       uses: guardian/actions-setup-node@main

  #     - name: Install dependencies
  #       uses: bahmutov/npm-install@v1

  #     - name: Fetch build
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: bundle
  #         path: bundle/dist

  #     - name: Release
  #       run: yarn semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         HUSKY: 0
