name: CI
on:
    push:
        branches-ignore:
            - 'gh-pages'
jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js
              shell: bash -l {0}
              run: nvm install

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Run unit tests
              run: 'yarn test --coverage --ci'

            - name: Report coverage
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              shell: bash -l {0}
              run: nvm install

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Lint files
              run: yarn lint
    types:
        name: Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              shell: bash -l {0}
              run: nvm install

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Check types
              run: yarn tsc
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build package
              run: yarn build
