name: E2E Cypress
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: 'e2e-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: E2E Cypress
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]
    steps:
      # Commercial
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./commercial

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: './commercial/.nvmrc'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./commercial

      # DCR
      - name: Checkout DCR
        uses: actions/checkout@v3
        with:
          repository: guardian/dotcom-rendering
          path: ./dcr

      - name: Setup DCR node
        uses: actions/setup-node@v3
        with:
          node-version-file: './dcr/.nvmrc'

      - name: Install DCR dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./dcr
        env:
          NODE_ENV: production

      - name: Build DCR
        run: make build
        working-directory: ./dcr/dotcom-rendering

      - name: Start DCR server
        run: make start-ci & npx wait-on -v -i 1000 http://localhost:3030
        working-directory: ./dcr/dotcom-rendering
        env:
          PORT: 3030
          COMMERCIAL_BUNDLE_URL: http://localhost:3031/graun.standalone.commercial.js

      - name: Start Commercial server
        run: yarn serve & npx wait-on -v -i 1000 http://localhost:3031/graun.standalone.commercial.js
        working-directory: ./commercial

      - name: Run Cypress
        run: yarn cypress run --spec cypress/e2e/parallel-${{ matrix.group }}/*
        working-directory: ./commercial

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: commercial/cypress/videos

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: commercial/cypress/screenshots
