name: E2E Visual
on: workflow_dispatch
    # pull_request:
    #     paths:
    #         - static/src/javascripts/projects/common/modules/commercial/**
    #         - static/src/javascripts/projects/commercial/**
    #         - static/src/javascripts/projects/common/modules/spacefinder-*
    #         - commercial/**
    #         - cypress/**
    #         - cypress.config.ts
    #         - .github/workflows/commercial-e2e-visual.yml

concurrency:
    group: 'commercial-e2e-visual-${{ github.head_ref }}'
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            # Commercial
            - name: Checkout
              uses: actions/checkout@v3
              with:
                path: ./commercial

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version-file: "./commercial/.nvmrc"

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              with:
                working-directory: ./commercial

            # DCR
            - name: Checkout DCR
              uses: actions/checkout@v3
              with:
                  repository: guardian/dotcom-rendering
                  path: ./dcr

            - name: Setup DCR node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './dcr/.nvmrc'

            - name: Install DCR dependencies
              run: yarn install --frozen-lockfile
              with:
                  working-directory: ./dcr

            - name: Build DCR
              run: make build
              working-directory: ./dcr/dotcom-rendering

            - name: Start Commercial server
              run: yarn server & npx wait-on -v -i 1000 http://localhost:3031/graun.standalone.commercial.js
              working-directory: ./commercial/bundle

            - name: Start DCR server
              run: make start-ci & npx wait-on -v -i 1000 http://localhost:3030
              working-directory: ./dcr/dotcom-rendering
              env:
                  PORT: 3030
                  COMMERCIAL_BUNDLE_URL: http://localhost:3031/graun.standalone.commercial.js

            - name: Run Percy Visual Regression Tests
              run: yarn cypress:run:snapshot
              working-directory: ./e2e
              env:
                  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

            - name: Wait for Percy Snapshots
              run: yarn percy build:wait --verbose --fail-on-changes --project ced09b1a/commercial --commit ${{ github.event.pull_request.head.sha }} --timeout 900000 --interval 5000
              working-directory: ./e2e
              env:
                  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: cypress-videos
                  path: ./e2e/cypress/videos

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: ./e2e/cypress/screenshots
